### ISSUE TITLE
Error in handling Helm charts with values yaml containing a list with different dictionaries

### ISSUE THREAD

**Issue by devdattakulkarni** [cloud-ark/kubeplus#1140]
When trying [Supabase Helm chart](https://github.com/bitnami/charts/tree/main/bitnami/supabase), we are seeing the following error when creating an instance of Supabase.

`error: error validating "sample-supabase.yaml": error validating data: ValidationError(Supabase.spec.kong.extraVolumes[0]): unknown field "configMap" in kubeplus.platformapi.v1alpha1.Supabase.spec.kong.extraVolumes;`

Supabase Helm chart has the following property definition in values.yaml

```
extraVolumes:
  - name: declarative-conf-template
    configMap:
      name: "{{ .Release.Name }}-kong-declarative-config"
  - name: rendered-declarative-conf
    emptyDir: {}
```

extraVolumes is a key whose value is a list of dictionaries, with each dictionary having a different structure.

KubePlus needs to correctly handle such dictionaries when registering a CRD.
